doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            point: App\Types\PointType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                ST_DWithin: 'Jsor\Doctrine\PostGIS\Functions\ST_DWithin'
                ST_MakePoint: 'Jsor\Doctrine\PostGIS\Functions\ST_MakePoint'
                ST_SetSRID: 'Jsor\Doctrine\PostGIS\Functions\ST_SetSRID'
                ST_Point: 'Jsor\Doctrine\PostGIS\Functions\ST_Point'
                ST_DistanceSphere: 'Jsor\Doctrine\PostGIS\Functions\ST_DistanceSphere'
                ST_Distance: 'Jsor\Doctrine\PostGIS\Functions\ST_Distance'

        mappings:
            Chat:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Chat/Domain/Entity'
                prefix: 'App\Modules\Chat\Domain\Entity'
                alias: Chat
            City:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/City/Domain/Entity'
                prefix: 'App\Modules\City\Domain\Entity'
                alias: City
            Company:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Company/Domain/Entity'
                prefix: 'App\Modules\Company\Domain\Entity'
                alias: Company
            Filter:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Filter/Domain/Entity'
                prefix: 'App\Modules\Filter\Domain\Entity'
                alias: Filter
            Load:
                dir: '%kernel.project_dir%/src/Modules/Load/Domain/Entity'
                is_bundle: false
                prefix: 'App\Modules\Load\Domain\Entity'
                alias: Load
            Transport:
                dir: '%kernel.project_dir%/src/Modules/Transport/Domain/Entity'
                is_bundle: false
                prefix: 'App\Modules\Transport\Domain\Entity'
                alias: Transport
            User:
                dir: '%kernel.project_dir%/src/Modules/User/Domain/Entity'
                is_bundle: false
                prefix: 'App\Modules\User\Domain\Entity'
                alias: User

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
