lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: email
    token_ttl: 43200

    token_extractors:
        authorization_header:
            enabled: false
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: '%env(JWT_NAME)%'

        split_cookie:
            enabled: false
            cookies:
                - jwt_hp
                - jwt_s

    set_cookies:
        '%env(JWT_NAME)%':
            lifetime: null
            samesite: lax
            path: /
            domain: null
            secure: false
            httpOnly: false
            partitioned: false

    remove_token_from_body_when_cookies_used: false
